spring:
  application:
     name: users-service
  jpa:
     show-sql: true
  jackson:
     date-format: dd-MM-yyyy
  hornetq:
       mode: native
       host: localhost
       port: 5455

server:
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

timelineService:
    baseUrl: http://localhost:1000


