spring:
  application:
     name: timeline-service
  jpa:
     show-sql: true
  hornetq:
     mode: native
     host: localhost
     port: 5455

server:
  port: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
      



